In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import pairwise_distances

### Pair Problem #1
You are given the following three documents:

In [13]:
text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]

Transform this data into a bag of words representation, with simple counts. How informative is this format? How much information do you have about individual words?  

In [14]:
vect = CountVectorizer()
data = vect.fit_transform(text).todense()

In [15]:
print(vect.get_feature_names())

['harry', 'potter', 'stormtrooper', 'wookie']


In [16]:
print(data)

[[0 0 1 1]
 [0 0 3 3]
 [1 1 0 0]]


Calculate Euclidean and cosine distances between each pair of documents. How do these distances relate to your intuition for the documents' similarities?  

In [17]:
print(pairwise_distances(data, metric='euclidean'))
print('-')
print(pairwise_distances(data, metric='cosine').round(2))

[[0.         2.82842712 2.        ]
 [2.82842712 0.         4.47213595]
 [2.         4.47213595 0.        ]]
-
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [18]:
#TAKEAWAY: Euclidean distance not good for use with language

Calculate one minus the cosine distance between each pair of de-meaned documents, and the Pearson correlation coefficient between each pair of documents. How are they related? Is this a coincidence? Find a counterexample or prove that there isn't one. 


In [22]:
print(1 - pairwise_distances(data - data.mean(axis=1), metric='cosine'))
#'De-meaning' == 'Subtracting the mean'

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]


In [21]:
print(np.corrcoef(data))

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]


### Pair Problem #2  
Imagine a data matrix with three rows and two columns. Each row represents an observation, and each column represents a feature. (This is our usual convention.)  

Imagine subtracting out the column means.  


In [28]:
# 3 observations
A = [[25, 30], [29, 40], [39, 78]]
data = pd.DataFrame(A)

# subtract means (on a column-basis)
means = np.mean(data)
delt = data - means

In [27]:
means

0    31.000000
1    49.333333
dtype: float64

In [26]:
delt

0          1
0 -6.0 -19.333333
1 -2.0  -9.333333
2  8.0  28.666667

Imagine multiplying the transpose of this matrix by itself.  Don't just imagine it—write this out!  


In [29]:
covar = np.dot(delt.T, delt)
covar

array([[ 104.        ,  364.        ],
       [ 364.        , 1282.66666667]])

What familiar calculation is this? What result have you produced?

In [ ]:
# Covariance formula, sum of squared error (instead of x varying with itself, 
# we're seeing how x varies with y)

#If x varies, but y never varies, then our covariance would be zero
