In [2]:
import numpy as np

In [3]:
#A
#Only one solution
X = np.array([[2]])
y = np.array([8])
np.linalg.solve(X, y)

array([4.])

In [4]:
#B
#No Answers
X = np.array([[0]])
y = np.array([8])
np.linalg.solve(X, y)

LinAlgError: Singular matrix

In [10]:
#C
#INFINITE SOLUTIONS
X = np.array([[2,4]])
y = np.array([8])
np.linalg.solve(X, y)

LinAlgError: Last 2 dimensions of the array must be square

In [9]:
#D
X = np.array([[2, 4],[0,1]])
y = np.array([8,3])
np.linalg.solve(X, y)

array([-2.,  3.])

In [11]:
#E
#No solutions
X = np.array([[2, 4],[0,1],[9,5]])
y = np.array([8,3,1])
np.linalg.solve(X, y)

LinAlgError: Last 2 dimensions of the array must be square

In [12]:
#F
#Actually has infinite solutions
X = np.array([[2, 2],[3,3]])
y = np.array([4,6])
np.linalg.solve(X, y)

array([0., 2.])

In [ ]:
#G
#Can't compare cats to dogs, different scales (if it were changed so there were
#a bridge between the words and numbers, would be different)
X = [['dog'],    y = [8,
     ['cat']]         6]

In [13]:
#H
#X is the identity matrix, so w = y
X = np.array([[1, 0],[0,1]])
y = np.array([8,6])
np.linalg.solve(X, y)


array([8., 6.])

In [14]:
#I
#INFINITE SOLUTIONS
X = np.array([[1,1,0],[1,0,1]])
y = np.array([8,6])
np.linalg.solve(X, y)

LinAlgError: Last 2 dimensions of the array must be square

In [15]:
#J
#Just the one solution
X = np.array([[1,0],[1,1]])
y = np.array([8,6])
np.linalg.solve(X, y)

array([ 8., -2.])